import Head from 'next/head'
import React from 'react';
import Button from './button';
import styles from '../styles/Home.module.css'


export default function Home() {
  const buttonOneContent = 'My Personal Page';
  const buttonTwoContent = 'Glorpy :)';
  return (
    <>
      <Head>
        <title>t-browne.me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          <h1> Hello Tomathy</h1>
          <hr/>
          <p> This is my website in which i site all my webs</p>
        </div>
        <div className={styles.buttonContainer}>
          <Button destination="https://tbrowne.me" content={buttonOneContent}/>
          <Button destination='https://natty-light.github.io' content={buttonTwoContent}/>
        </div>
      </main>
    </>
  )
}
